name: Auto OCR
on:
  schedule:
    - cron: "0 12 * * *"  # 12h trưa hàng ngày
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-vie
          
      - name: Generate image and run OCR
        run: |
          python -c "
          from PIL import Image, ImageDraw
          img = Image.new('RGB', (400, 200), 'white')
          d = ImageDraw.Draw(img)
          d.text((10, 10), 'ẢNH TỰ ĐỘNG $(date +"%d/%m/%Y")', fill='black')
          img.save('sample.png')
          "
          tesseract sample.png -l vie output.txt
          echo "\n--- $(date +"%d/%m %H:%M") ---" >> docs/results.txt
          cat output.txt >> docs/results.txt
          
      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/results.txt
          git commit -m "Update OCR results"
          git push
